[workspace]
resolver = "2"
members = [
    "survivor-app",
    "survivor-wasm",
]

[workspace.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
console_error_panic_hook = "0.1"
wee_alloc = "0.4"